#!/usr/bin/env python3
"""gen_skills_min.py — generate compressed machine-readable skill indexes.

Reads registry/skills.yaml + registry/cross-links.yaml + each skill's SKILL.md
and emits:

  registry/skills.min.yaml  — per-skill compressed index for cache-friendly
                              agent onboarding (<2000-token budget)
  registry/triggers.yaml    — reverse index: keyword -> [skill ids]

Idempotent: rerunning regenerates identical bytes from the registries.
Deterministic: no randomness; every derived field uses fixed rules and sorts.

Field derivation:
  tokens           = SKILL.md activation cost (frontmatter + body) using the
                     token_measure.py blended heuristic (chars/3.5 + words/1.3)
  std_version      = FIRST match of C99|C11|C17|C23|C++98..C++23|Rust 2018..2024|
                     NASM 2.x|GCC 1x|Zig 0.x in SKILL.md (case-insensitive)
  last_verified    = meta.updated from registry/skills.yaml
  triggers         = first 5 distinctive keywords from the frontmatter
                     description (split on non-alphanumeric, stopword-filtered,
                     deduped in order of appearance, then sorted)
  negative_triggers= known high-level terms found in the 'When not to use'
                     section (python, javascript, js, web, high-level,
                     business logic, application code, GUI, database, UI)
  priority_rules   = first 2 fragments from 'How to verify' bullets / fenced
                     code lines, each trimmed to <=60 chars
  requires         = sorted ids of require edges FROM this skill in
                     registry/cross-links.yaml

Usage:
  python tools/reports/gen_skills_min.py             # regenerate both files
  python tools/reports/gen_skills_min.py --skills    # skills.min.yaml only
  python tools/reports/gen_skills_min.py --triggers  # triggers.yaml only
"""
import os
import re
import sys
from collections import defaultdict

import yaml

ROOT = os.path.abspath(
    sys.argv[1] if len(sys.argv) > 1 and os.path.isdir(sys.argv[1]) else
    os.path.join(os.path.dirname(__file__), "..", "..")
)

OUT_SKILLS = os.path.join(ROOT, "registry", "skills.min.yaml")
OUT_TRIGGERS = os.path.join(ROOT, "registry", "triggers.yaml")

HEADER = "# GENERATED by tools/reports/gen_skills_min.py — DO NOT EDIT BY HAND."

# --- token estimation (mirrors tools/tokens/token_measure.py fallback) ---
# The blended heuristic is used instead of importing token_measure.py so the
# output is byte-identical on every machine (tiktoken presence would otherwise
# change the numbers). Same formula, no randomness.


def est_tokens(text: str) -> int:
    chars = len(text)
    words = len(text.split())
    return max(1, round(chars / 3.5 * 0.6 + words / 1.3 * 0.4))


def activation_tokens(sk_text: str) -> int:
    """Replicates token_measure.py measure(): activation = metadata + body."""
    meta = 0
    total = est_tokens(sk_text)
    if sk_text.startswith("---"):
        m = re.match(r"^---\n(.*?)\n---\n", sk_text, re.S)
        if m:
            meta = est_tokens(m.group(1))
            total = est_tokens(sk_text[m.end():])
    return meta + total


# --- std_version scan (best-effort, first match wins) ---
STD_RE = re.compile(
    r"C\+\+23|C\+\+20|C\+\+17|C\+\+14|C\+\+11|C\+\+03|C\+\+98|C\+\+|"
    r"C99|C11|C17|C23|"
    r"Rust 2024|Rust 2021|Rust 2018|"
    r"NASM 2\.x|NASM 2\.\d+|"
    r"GCC 1\d|GCC 2\d|"
    r"Zig 0\.\d+",
    re.IGNORECASE,
)


def derive_std_version(text: str):
    m = STD_RE.search(text)
    return m.group(0) if m else None


# --- triggers from frontmatter description ---
STOPWORDS = {
    "use", "the", "when", "how", "a", "an", "and", "or", "of", "to", "for",
    "in", "on", "with", "write", "writing", "reading", "reviewing", "debugging",
    "code", "that", "may", "is", "are", "be", "not", "do", "can", "will",
    "this", "task", "agent", "it", "its", "as", "at", "by", "from", "if",
    "then", "than", "was", "were", "has", "have", "had", "been", "also",
    "such", "more", "most", "any", "all", "both", "each", "which", "who",
    "whom", "you", "we", "they", "their", "them", "there", "where", "what",
    "why", "does", "did", "done", "using", "used", "requires", "required",
    "etc", "via", "vs", "about", "across", "against", "between", "within",
    "without", "through", "upon", "towards", "under", "into", "during",
    "before", "after", "above", "below", "among",
}

TRIGGER_LIMIT = 5


def derive_triggers(desc: str):
    seen = set()
    out = []
    for tok in re.split(r"[^a-z0-9]+", (desc or "").lower()):
        if not tok or tok in STOPWORDS or len(tok) < 2 or tok in seen:
            continue
        if tok.isdigit():
            continue
        seen.add(tok)
        out.append(tok)
        if len(out) >= TRIGGER_LIMIT:
            break
    return sorted(out)


# --- negative_triggers from 'When not to use' section ---
NEGATIVE_TERMS = [
    "python", "javascript", "js", "web", "high-level",
    "business logic", "application code", "gui", "database", "ui",
]


def extract_section(text: str, name: str) -> str:
    m = re.search(r"^##\s+" + re.escape(name) + r"\s*$", text, re.M)
    if not m:
        return ""
    start = m.end()
    nxt = re.search(r"^##\s+", text[start:], re.M)
    end = start + (nxt.start() if nxt else len(text))
    return text[start:end]


def derive_negative_triggers(text: str):
    section = extract_section(text, "When not to use").lower()
    found = []
    for term in NEGATIVE_TERMS:
        pattern = r"\b" + re.escape(term.lower()) + r"\b"
        if re.search(pattern, section):
            found.append(term)
    return sorted(found)


# --- priority_rules from 'How to verify' section ---
FRAG_LIMIT = 60
RULE_COUNT = 2


def derive_priority_rules(text: str):
    section = extract_section(text, "How to verify")
    rules = []
    for line in section.splitlines():
        if len(rules) >= RULE_COUNT:
            break
        s = line.strip()
        if not s.startswith(("- ", "* ")):
            continue
        frag = re.sub(r"\s+", " ", s[2:].strip())
        if frag:
            rules.append(frag[:FRAG_LIMIT])
    if len(rules) < RULE_COUNT:
        in_fence = False
        for line in section.splitlines():
            if len(rules) >= RULE_COUNT:
                break
            s = line.strip()
            if s.startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence and s:
                frag = re.sub(r"\s+", " ", s)
                rules.append(frag[:FRAG_LIMIT])
    return rules or ["verify per skill instructions"]


# --- yaml value formatting: flat 'key: value', inline lists ---
def fmt_scalar(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    if re.fullmatch(r"\d{4}-\d{2}-\d{2}", s):
        return "'" + s + "'"
    if re.fullmatch(r"[A-Za-z0-9_.\-/]+", s):
        return s
    return "'" + s.replace("'", "''") + "'"


def fmt_list(items):
    return "[" + ", ".join(fmt_scalar(i) for i in items) + "]"


def load_registry():
    skills = yaml.safe_load(open(os.path.join(ROOT, "registry", "skills.yaml"), encoding="utf-8"))
    cross = yaml.safe_load(open(os.path.join(ROOT, "registry", "cross-links.yaml"), encoding="utf-8"))
    return skills, cross


def build_entries(skills_data, cross_links):
    updated = skills_data.get("meta", {}).get("updated")
    require_map = defaultdict(list)
    for edge in cross_links.get("cross_links", []):
        if edge.get("rel") == "require" and edge.get("from") and edge.get("to"):
            require_map[edge["from"]].append(edge["to"])

    entries = []
    for sk in skills_data.get("skills", []):
        sk_path = os.path.join(ROOT, sk["path"].replace("/", os.sep), "SKILL.md")
        text = ""
        try:
            text = open(sk_path, encoding="utf-8").read()
        except OSError:
            text = ""
        fm_m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
        desc = ""
        if fm_m:
            dm = re.search(r"^description:\s*(.+)$", fm_m.group(1), re.M)
            if dm:
                desc = dm.group(1).strip()
        entries.append({
            "id": sk["id"],
            "domain": sk.get("domain", ""),
            "type": sk.get("type", ""),
            "stability": sk.get("stability", ""),
            "tokens": activation_tokens(text) if text else 0,
            "std_version": derive_std_version(text) if text else None,
            "last_verified": updated,
            "triggers": derive_triggers(desc),
            "negative_triggers": derive_negative_triggers(text),
            "priority_rules": derive_priority_rules(text),
            "requires": sorted(require_map.get(sk["id"], [])),
            "path": sk["path"],
        })
    return sorted(entries, key=lambda e: e["id"]), updated


def emit_skills_min(entries, updated):
    lines = [
        HEADER,
        "# Runs: python tools/reports/gen_skills_min.py",
        "# tokens=SKILL.md activation cost (token_measure.py heuristic);",
        "# std_version=first C99/C11/C17/C23/C++/Rust-edition/NASM-2.x/GCC-1x/Zig-0.x match in SKILL.md;",
        "# triggers=first 5 keywords of frontmatter description (stopword-filtered, sorted);",
        "# negative_triggers=high-level terms found in 'When not to use';",
        "# priority_rules=first 2 fragments from 'How to verify' (<=60 chars);",
        "# requires=require edges from registry/cross-links.yaml (sorted).",
        "meta:",
        "  generated_by: tools/reports/gen_skills_min.py",
        "  updated: " + fmt_scalar(updated),
        "  total: " + str(len(entries)),
        "skills:",
    ]
    for e in entries:
        lines.append("- id: " + fmt_scalar(e["id"]))
        lines.append("  domain: " + fmt_scalar(e["domain"]))
        lines.append("  type: " + fmt_scalar(e["type"]))
        lines.append("  stability: " + fmt_scalar(e["stability"]))
        lines.append("  tokens: " + str(e["tokens"]))
        lines.append("  std_version: " + fmt_scalar(e["std_version"]))
        lines.append("  last_verified: " + fmt_scalar(e["last_verified"]))
        lines.append("  triggers: " + fmt_list(e["triggers"]))
        lines.append("  negative_triggers: " + fmt_list(e["negative_triggers"]))
        lines.append("  priority_rules: " + fmt_list(e["priority_rules"]))
        lines.append("  requires: " + fmt_list(e["requires"]))
        lines.append("  path: " + fmt_scalar(e["path"]))
    return "\n".join(lines) + "\n"


def build_triggers(entries):
    pos = defaultdict(set)
    neg = defaultdict(set)
    for e in entries:
        for kw in e["triggers"]:
            pos[kw].add(e["id"])
        for kw in e["negative_triggers"]:
            neg[kw].add(e["id"])
    return pos, neg


def emit_triggers(pos, neg, updated):
    lines = [
        HEADER,
        "# Reverse index: keyword -> [skill ids]. Source: registry/skills.min.yaml.",
        "meta: {generated_by: tools/reports/gen_skills_min.py, updated: " + fmt_scalar(updated) + "}",
        "triggers:",
    ]
    for kw in sorted(pos):
        lines.append("  " + fmt_scalar(kw) + ": " + fmt_list(sorted(pos[kw])))
    lines.append("negative_triggers:")
    for kw in sorted(neg):
        lines.append("  " + fmt_scalar(kw) + ": " + fmt_list(sorted(neg[kw])))
    return "\n".join(lines) + "\n"


def write(path, content):
    open(path, "w", encoding="utf-8", newline="\n").write(content)
    print(f"Wrote {os.path.relpath(path, ROOT)} ({len(content.splitlines())} lines)")


def main() -> int:
    skills_data, cross_links = load_registry()
    entries, updated = build_entries(skills_data, cross_links)

    args = [a for a in sys.argv[1:] if a.startswith("--")]
    do_skills = "--skills" in args or not args
    do_triggers = "--triggers" in args or not args

    if do_skills:
        write(OUT_SKILLS, emit_skills_min(entries, updated))
    if do_triggers:
        pos, neg = build_triggers(entries)
        write(OUT_TRIGGERS, emit_triggers(pos, neg, updated))

    print(f"Generated {len(entries)} skill entries (updated={updated})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
