#!/usr/bin/env python3
"""gen_landing_data.py — build docs/assets/skills.js (window.SKILLS) for the landing page.

Parses registry/skills.yaml (stability) and each skills/<domain>/<id>/SKILL.md
frontmatter (name, description), emits a compact JS array sorted by domain/id.
"""
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pip install PyYAML")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

with open(os.path.join(ROOT, "registry", "skills.yaml"), encoding="utf-8") as f:
    registry = yaml.safe_load(f)

stability = {}
for s in registry.get("skills", []):
    stability[s.get("id")] = s.get("stability", "researched")

FRONT = re.compile(r"^---\s*\n(.*?)\n---", re.S | re.M)
FIELD = re.compile(r"^(\w+):\s*(.*)$", re.M)


def front_field(text: str, key: str) -> str:
    m = FRONT.search(text)
    if not m:
        return ""
    fm = m.group(1)
    f = FIELD.search(fm, re.M)
    # find the specific key
    for line in fm.splitlines():
        if line.startswith(key + ":"):
            return line.split(":", 1)[1].strip().strip('"').strip("'")
    return ""


skills = []
skills_root = os.path.join(ROOT, "skills")
for domain in sorted(os.listdir(skills_root)):
    dpath = os.path.join(skills_root, domain)
    if not os.path.isdir(dpath):
        continue
    for sid in sorted(os.listdir(dpath)):
        skill_dir = os.path.join(dpath, sid)
        md = os.path.join(skill_dir, "SKILL.md")
        if not os.path.isdir(skill_dir) or not os.path.exists(md):
            continue
        with open(md, encoding="utf-8") as f:
            text = f.read()
        name = front_field(text, "name") or sid
        desc = front_field(text, "description") or ""
        if len(desc) > 190:
            desc = desc[:187] + "…"
        skills.append({
            "id": sid,
            "domain": domain,
            "name": name,
            "stability": stability.get(sid, "researched"),
            "desc": desc,
        })

skills.sort(key=lambda s: (s["domain"], s["id"]))

out = os.path.join(ROOT, "docs", "assets", "skills.js")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w", encoding="utf-8") as f:
    f.write("/* Generated by tools/reports/gen_landing_data.py — do not edit. */\n")
    f.write("window.SKILLS = ")
    f.write(json.dumps(skills, ensure_ascii=False, separators=(",", ":")))
    f.write(";\n")

print(f"wrote {out}: {len(skills)} skills")
