// GOOD: module with a GPL license tag, correct vermagic retention, and proper
// init/exit. GPL-only exports resolve because MODULE_LICENSE("GPL") is present.
// The vermagic is generated by Kbuild — never stripped.
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>

extern int gpl_only_api(void);

static int __init good_init(void)
{
	pr_info("good_mod loaded, api=%d\n", gpl_only_api());
	return 0;
}

static void __exit good_exit(void)
{
	pr_info("good_mod unloaded\n");
}

module_init(good_init);
module_exit(good_exit);

MODULE_LICENSE("GPL");
MODULE_AUTHOR("TrothByte examples");
MODULE_DESCRIPTION("Canonical out-of-tree module shape");
MODULE_VERSION("1.0");
